# # Aliases
alias cl="clear && pokemon-colorscripts -r"
alias pc="pokemon-colorscripts"
alias c="clear"
alias watch="sass --style compressed --watch"
# alias stb="~/static-project-builder/./static-project-builder.sh"
alias sz="clear && source ~/.zshrc"
# alias vim="neovide"
alias vi="nvim"
alias cat="bat"
alias l="TERM=dumb lsd"
alias ll="l -l"
alias la="l -la"
alias lt="l --tree"

# # Location Aliases
alias home='cd /mnt/e/Amal/'
alias desktop="cd /mnt/e/Amal/Desktop"
alias documents="cd /mnt/e/Amal/Documents"
alias downloads="cd /mnt/e/Amal/Downloads"
alias projects="cd /mnt/e/Amal/Documents/Programming/My\ Projects"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=9999
SAVEHIST=9999
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/amal/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %r/%S %b %m%u%c "
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[magenta]%} %b%{$fg[blue]%})"

# format our main prompt for hostname current folder, and permissions.
PROMPT="%B%{$fg[green]%}amal$fg[magenta]%} ϟ %{$fg[yellow]%}[ %{$fg[red]%}%c%{$fg[yellow]%} ]%{$fg[green]%} :%{$reset_color%}"
PROMPT+="\$vcs_info_msg_0_%{$reset_color%}%b "

# pokemon colorscripts on startup
pc -r

# Config for Cli tools (ensure that fd is installed)
# fzf fuzzy find
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git "
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" # default fzf (folders and files)
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git" # fzf navigate to folders
# default fzf settings
export FZF_DEFAULT_OPTS="--height 50% --layout=reverse --border=rounded --preview-window=border-rounded --no-scrollbar --info=right --cycle --prompt='▶ ' --color=bg+:#311d42,gutter:-1,hl:#26f96b,fg:#b267e6,bg:-1,hl+:#26f96b,fg+:#b267e6,pointer:#b267e6,prompt:#f92672,border:#b267e6,query:#b267e6,info:#4e2d65,spinner:#f9a826,scrollbar:#4e2d65,scrollbar:#4e2d65,separator:#4e2d65,label:#b267e6"
export FZF_CTRL_T_OPTS="--preview 'bat --theme='aura-theme' --color=always -n --line-range :500 {}' --border-label=' fuzzy find '"
export FZF_ALT_C_OPTS="--preview 'eza --icons=always --tree --color=always {} | head -200' --border-label=' change directory '"

# Add ~/.local/bin to PATH (auto-generated by pokeget installer)
export PATH="$HOME/.local/bin:$PATH"
